config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'



  get 'books' => "books#index"
  post 'books' =>'books#create'
  get 'books/:id' =>'books#show'
  get 'books/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    book = Book.new (book_params)
    book.save
    redirect_to '/books'
  end


  def show
    @book=Book.find(params[:id])
  end

  def edit
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books</h1>



<table>

  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
  <% @books.each do |book| %>
  <tr>
    <th><%= book.title %></th>
    <th><%= book.body %></th>
    <th>show</th>
    <th>edit</th>
    <th>destroy</th>
  </tr>
  <% end %>
</table>


<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :Title %>
	
  <h4>本文</h4>
  <%= f.text_area :Body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :Title %>
	
  <h4>本文</h4>
  <%= f.text_area :Body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p>book was successfully created</p>


<p>Title <%=@book.title %></p>
<p>Body <%=@book.body %></p>

app/views/homes/top.html.erb
<div class="intro">
<h1>ようこそ Bookers へ！</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
   印象を共有し交換することができます</p>

<p><%= link_to "start", books_path %></p>

   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BokkersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>